import * as fs from 'fs';
import * as path from 'path';

const dataDir = path.join(__dirname, '..', 'src', 'data');
const busFilesPath = path.join(dataDir, 'bus-files.json');
const outputPath = path.join(dataDir, 'index.ts');

const busFiles: string[] = JSON.parse(fs.readFileSync(busFilesPath, 'utf-8'));

const requireEntries = busFiles
  .map((file) => {
    const safeKey = file.replace(/'/g, "\\'");
    return `  '${safeKey}': require('./${file}'),`;
  })
  .join('\n');

const output = `// Auto-generated by scripts/generate-data-index.ts
// Do not edit manually

const busDataMap: Record<string, any> = {
${requireEntries}
};

export const busFiles: string[] = ${JSON.stringify(busFiles, null, 2)};

export function getBusData(fileName: string): any {
  return busDataMap[fileName] ?? null;
}
`;

fs.writeFileSync(outputPath, output, 'utf-8');
console.log(`Generated data index with ${busFiles.length} entries at ${outputPath}`);
